
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collections;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ahmed EL-Halawany
 */
public class Student_Mode extends javax.swing.JFrame {
    final void FillLinkedList()
    {
        try {
            String url = "jdbc:mysql://localhost:3306/quiz";
            String username = "root";
            String password = "root";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stmt = con.createStatement();
            String Query = "SELECT * FROM questions";
            ResultSet rs = stmt.executeQuery(Query);

            while (rs.next()) {
                if (rs.getString(1).equalsIgnoreCase("fill in the blank")) {
                    Quiz.q.add(new FillInBlankQuestion(rs.getString(2), rs.getString(3)));
                } else if (rs.getString(1).equalsIgnoreCase("short answer")) {
                    Quiz.q.add(new ShortAnswerQuestion(rs.getString(2), rs.getString(3)));
                } else if (rs.getString(1).equalsIgnoreCase("true or false")) {
                    if (rs.getString(3).equalsIgnoreCase("true")) {
                        Quiz.q.add(new TrueFalseQuestion(rs.getString(2), true));
                    } else if (rs.getString(3).equalsIgnoreCase("false")) {
                        Quiz.q.add(new TrueFalseQuestion(rs.getString(2), false));
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    /**
     * Creates new form Student_Mood
     */
    public Student_Mode() {
        seticon();
        initComponents();
        this.setLocationRelativeTo(null);
        btn_fin.setEnabled(false);
        txt_ans.requestFocusInWindow();

        FillLinkedList();
        Collections.shuffle(Quiz.q);
        Quiz.que = Quiz.q.get(Quiz.i);
        txt_ques.setText(Quiz.que.get_Question());
        Quiz.i++;
        Quiz.size = Quiz.q.size();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_fin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ques = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ans = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Mode Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btn_fin.setBackground(new java.awt.Color(255, 255, 255));
        btn_fin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_fin.setForeground(new java.awt.Color(0, 0, 204));
        btn_fin.setText("Finish The Quiz");
        btn_fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Answer :");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question :");

        txt_ques.setEditable(false);
        txt_ques.setColumns(20);
        txt_ques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ques.setRows(6);
        jScrollPane1.setViewportView(txt_ques);

        btn_submit.setBackground(new java.awt.Color(255, 255, 255));
        btn_submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(0, 0, 204));
        btn_submit.setText("Submit Answer");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        btn_submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_submitKeyTyped(evt);
            }
        });

        txt_ans.setColumns(20);
        txt_ans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ans.setForeground(new java.awt.Color(255, 0, 0));
        txt_ans.setRows(5);
        jScrollPane2.setViewportView(txt_ans);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_fin, btn_submit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finActionPerformed
        Quiz.answer = txt_ans.getText();
        if (Quiz.answer == null) {
            txt_ques.setText(null);
            Quiz.que = Quiz.q.get(Quiz.i);
            txt_ques.setText(Quiz.que.get_Question());
            Quiz.i++;
        } else {
            if (Quiz.answer.equalsIgnoreCase("true")) {
                Quiz.bans = true;
                Quiz.ca = Quiz.que.check_Answer(Quiz.bans);
            } else if (Quiz.answer.equalsIgnoreCase("false")) {
                Quiz.bans = false;
                Quiz.ca = Quiz.que.check_Answer(Quiz.bans);
            } else {
                Quiz.ca = Quiz.que.check_Answer(Quiz.answer);
            }
            if (Quiz.ca == true) {
                Quiz.score++;
            }
        //if (Quiz.flag >= 1) {
          //  Quiz.size -= Quiz.oldsize;
        //}
        Quiz.score1 = (((float) Quiz.score / (float) Quiz.size) * (float) 100);
        Quiz.score1 = Math.round(Quiz.score1 * 100) / (float) 100;
        if (Quiz.score1 >= 50.0) {
            Quiz.flag += 1;
            JOptionPane.showMessageDialog(null, "You Have Finished The Quiz.\nYou Have Answered " + Quiz.score + " Questions Right Out Of " + Quiz.size + " Questions.\nYour Final Score Is " + Quiz.score1 + " %\nYou Have Passed The Quiz.");
        } else {
            Quiz.flag += 1;
            JOptionPane.showMessageDialog(null, "You Have Finished The Quiz.\nYou Have Answered " + Quiz.score + " Questions Right Out Of " + Quiz.size + " Questions.\nYour Final Score Is " + Quiz.score1 + " %\nYou Have Failed The Quiz.");
        }
        try {
            String url = "jdbc:mysql://localhost:3306/quiz";
            String username = "root";
            String password = "root";
            Connection con1 = DriverManager.getConnection(url, username, password);
            Statement stmt1 = con1.createStatement();
            String Query1 = "UPDATE student SET score = '" + Quiz.score1 + "' WHERE score = '" + Quiz.res + "'";
            stmt1.execute(Query1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        Quiz.score = 0;
        Quiz.score1 = 0;
       //Quiz.oldsize = Quiz.size;
        //this.setVisible(false);
        //new Quiz_GUI().setVisible(true);
        System.exit(0);
        }
    }//GEN-LAST:event_btn_finActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        txt_ans.requestFocusInWindow();
        Quiz.answer = txt_ans.getText();
        if (Quiz.answer == null) {
            txt_ques.setText(null);
            Quiz.que = Quiz.q.get(Quiz.i);
            txt_ques.setText(Quiz.que.get_Question());
            Quiz.i++;
        } else {
            if (Quiz.answer.equalsIgnoreCase("true")) {
                Quiz.bans = true;
                Quiz.ca = Quiz.que.check_Answer(Quiz.bans);
            } else if (Quiz.answer.equalsIgnoreCase("false")) {
                Quiz.bans = false;
                Quiz.ca = Quiz.que.check_Answer(Quiz.bans);
            } else {
                Quiz.ca = Quiz.que.check_Answer(Quiz.answer);
            }
            if (Quiz.ca == true) {
                Quiz.score++;
            }
            txt_ques.setText(null);
            txt_ans.setText(null);
            Quiz.que = Quiz.q.get(Quiz.i);
            txt_ques.setText(Quiz.que.get_Question());
            Quiz.i++;
            if (Quiz.i == Quiz.size) {
                btn_submit.setEnabled(false);
                btn_fin.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_submitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_submitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_submitKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Mode().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fin;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_ans;
    private javax.swing.JTextArea txt_ques;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("quiz.jpg")));
    }
}
